name: survivor_hub
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  intl: ^0.18.1
  google_fonts: ^6.1.0
  video_player: ^2.2.12
  image_picker: ^1.0.4
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.0
  http: ^1.0.0
  screen_protector: ^1.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # ✅ Added this

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/banner1.jpg
    - assets/banner2.jpg
    - assets/banner3.jpg
    - assets/1v1.jpg
    - assets/2v2.jpg
    - assets/4v4.jpg
    - assets/6v6.jpg
    - assets/intro_video.mp4
    - assets/qrcodes/

flutter_icons:   # ✅ Added this block
  android: true
  ios: true
  image_path: "assets/logo.png"
